masastack/MASA.TSC

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/DateTimeRangeToolbar/DateTimeRangeToolbar.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Team/TeamSearch.razor
=> Repair Team page component text uppercase

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/Charts/ServiceResponseAvgTime.razor.cs
fix:Service average response time missing time unit
fix:Average service response time. The maximum value is not fully displayed
=> fix:edit echars

src/Services/Masa.Tsc.Service.Admin/Application/Instruments/InstrumentCommandHandler.cs
=> fix:Under the same level, the dashboard model can not be repeated.resolved #227

src/Services/Masa.Tsc.Service.Admin/Program.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/MetricsExpression.razor
Indicator expression button position is inconsistent with the design draft
=> fix:Indicator expression button position is inconsistent with the design draft

src/Contracts/Masa.Tsc.Contracts.Admin/Dashboards/UpsertPanelDto.cs, src/Contracts/Masa.Tsc.Contracts.Admin/Infrastructure/Const/GlobalConfig.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/DashboardConfiguration.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Tabs/Models/UpsertTabItemPanelDto.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Tabs/TabsPanel.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Tabs/TabsPanel.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Text/TextPanel.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelGrids.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelGrids.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelSelect.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelSelect.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Configurations/ConfigurationTeamDetail.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/wwwroot/css/tsc.css, src/Web/Masa.Tsc.Web.Admin.Server/Pages/_Layout.cshtml
=> fix:If the service success rate is decimal, reserve two decimal places. resolved #192

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/ProjectCharts.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor
=> fix:Popover layout problem. resolved #316

src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor
=> fix:Content coverage problem. resolved #318

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/ProjectDetail.razor
=> fix:Project layout problem.resolved #319

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Team/HoneyCombGridItem.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Team/HoneyCombGridItem.razor.css, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor.css
Fix [Issue-312](https://github.com/masastack/MASA.TSC/issues/312)
=> Fix: modify team style.

src/Contracts/Masa.Tsc.Contracts.Admin/Teams/AppMonitorDto.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Team/MonitorCard.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Team/MonitorItemCard.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor.cs
Fix [Issue-314](https://github.com/masastack/MASA.TSC/issues/314)
=> Fix: add display ServiceCount for Normal in Team page.

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelGrids.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelSelect.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelSelect.razor.cs
=> fix:Tabs component Infinite addition

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/Charts/ServiceCallChart.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/Charts/ServiceResponseTimePercentile.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/Charts/ServiceResponseTimePercentile.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Masa.Tsc.Web.Admin.Rcl.csproj, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor
resolved #358 
需要等待 MasaBlazor发版这个pr：https://github.com/masastack/MASA.Blazor/pull/1218
=> fix:Team Project Detail page, refactor ServiceCallers、ServiceResponse、ErrorLogCounts

src/Contracts/Masa.Tsc.Contracts.Admin/Dashboards/GridstackChangeEventArgs.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Tabs/TabsPanel.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Topology/TopologyPanel.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Topology/TopologyPanel.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Gridstack/Gridstack.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Gridstack/Models/TscGridstackJSModule.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/wwwroot/js/antv-g6-helper.js, src/Web/Masa.Tsc.Web.Admin.Rcl/wwwroot/js/gridstack-helper.js
resolved https://github.com/masastack/MASA.TSC/issues/354
=> Fix/issues #354

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/DashboardConfiguration.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Models/PanelGridsExtensions.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelGrids.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Gridstack/Gridstack.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/wwwroot/js/gridstack-helper.js
=> fix:Add sequence problem. resolved #355

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Team/HoneyCombGridItem.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor.css
more button change to circle and some style. App item hover style
更多按钮改为圆形，应用Hover效果样式更改，边框对齐
=> fix: adjust topology style 

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/ChartPanelConfiguration.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Chart/PanelTooltip.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Trace/TscTraceList.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/DateTimeRangePicker/DateTimeRangePicker.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/DateTimeRangeToolbars/DateTimeRangeToolbar.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/DateTimeRangeToolbars/Dropdown.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/Charts/LogTraceStatiscChart.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Project/Charts/ServiceCallChart.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/SearchTextField.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Masa.Tsc.Web.Admin.Rcl.csproj, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor
fix-issues-491:update gloal icon button style
fix-issues-492:update MIcon to SIcon
=> fix-issues-491-492

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/ChartPanelConfiguration.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Log/LogPanel.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Log/LogPanel.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Trace/TscTraceList.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Trace/TscTraceSearch.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Trace/TscTraceSearch.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Masa.Tsc.Web.Admin.Rcl.csproj, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Dashboards/Dashboard.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Dashboards/Dashboard.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/Team.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor
Except as DateTimeRangePicker and DateTimeRangeToolbar
=> MButton -> SButton, -> SSearch. Upgrade Masa.Stack.Components package

src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor
=> fix:TeamProjectDialog component dividing line problem. resolved  392

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/Panel/Trace/TscTraceList.razor.cs, src/Web/Masa.Tsc.Web.Admin.Rcl/wwwroot/i18n/zh-CN.json
Fix [Issue-494](https://github.com/masastack/MASA.Stack.Components/issues/494)
=> fix: change name to upper

src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Pages/Teams/TeamProjectDialog.razor.cs
Fix [Issue-410](https://github.com/masastack/MASA.TSC/issues/410)
=> fix: ShowDetail feature in TeamProjectDialog

src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Dashboards/Configurations/PanelGrids.razor, src/Web/Masa.Tsc.Web.Admin.Rcl/Components/Gridstack/Gridstack.razor
=> style: change border style for panelgrids
